//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLojaWeb.Models
{
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class tab_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tab_usuario()
        {
            this.tab_produtos = new HashSet<tab_produtos>();
        }

        [Key]
        public long id_usuario { get; set; }
        public string nm_usuario { get; set; }
        [Display(Name = "Login")]
        [Required(ErrorMessage = "Informe o nome do usuário", AllowEmptyStrings = false)]
        public string login { get; set; }
        [Required(ErrorMessage = "Informe a senha do usuário", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string senha { get; set; }
        public string email { get; set; }
        public byte id_tipo_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tab_produtos> tab_produtos { get; set; }
        public virtual tab_tipo_usuario tab_tipo_usuario { get; set; }
    }
}
