//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLojaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_tipo_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tab_tipo_usuario()
        {
            this.tab_usuario = new HashSet<tab_usuario>();
        }
    
        public byte id_tipo_usuario { get; set; }
        public string ds_tipo_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tab_usuario> tab_usuario { get; set; }
    }
}
