//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysLojaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_produtos
    {
        public int id_produto { get; set; }
        public string ds_produto { get; set; }
        public System.DateTime dthr_cadastro { get; set; }
        public long usuario_cadastro { get; set; }
        public decimal preco_venda { get; set; }
        public byte[] foto { get; set; }
        public long id_categoria { get; set; }
        public sbyte status { get; set; }
    
        public virtual tab_categorias tab_categorias { get; set; }
        public virtual tab_usuario tab_usuario { get; set; }
    }
}
